### ISSUE TITLE
problems with rejectAnauthorized

### ISSUE THREAD

**Issue by edzillion** [coolaj86/nodejs-self-signed-certificate-example#3]
Hey

Thanks AJ. This really helped. Everything worked fine; got the lock icon in FF, which was using the correct cert etc.

But when  I added in requestCert and rejectUnauthorized I cannot connect to the server. I get 

`An error occurred during a connection to example-server.com:9800. SSL peer was unable to negotiate an acceptable set of security parameters. (Error code: ssl_error_handshake_failure_alert)`

Am I missing something? My eventual plan was to use this with a restify server to force https.

I also added in the CA, just in case. My options

`options = {
  key: fs.readFileSync(path.join(__dirname, 'certs', 'server', 'my-server.key.pem')),
  ca: [ fs.readFileSync(path.join(__dirname, 'certs', 'server', 'my-root-ca.crt.pem'))],
  cert: fs.readFileSync(path.join(__dirname, 'certs', 'server', 'my-server.crt.pem')),
  requestCert: true,
  rejectUnauthorized:true
};`

any ideas?

**Comment by edzillion** [comment]
I think I am misunderstanding ssl and am going to close this.

**Comment by coolaj86** [comment]
Hey, change `requestCert` to `false`. It only needs to be true for peer-ssl connections - like in an enterprise network where each device must validate itself to the server.

**Comment by edzillion** [comment]
yeah thanks I figured that out after a bit more reading
